# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  create_infrastructure: #job name
    docker: # it uses the docker executor
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure background infrastructure exist
          #echo environment variable
          command: |
            aws cloudformation deploy --template-file template.yml --stack-name my-stack

workflows:
  # workflow
  my_workflow:
    jobs:
      - create_infrastructure
